import 'package:flutter/material.dart';
List<String> schools = [];

class CollegeList extends StatefulWidget {
  const CollegeList({super.key});

  @override
  State<CollegeList> createState() => _CollegeListState();
}
class _CollegeListState extends State<CollegeList> {
  @override
  Widget build(BuildContext context) {
    return Center(
        child: Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          const Text(
            // ignore: deprecated_member_use
            textScaleFactor: 3.0,
            style: TextStyle(color: Colors.blue),
            'My College List',
          ),
          DropdownMenu(
            onSelected: (value) {
              schools.add(value.toString());
            },
            dropdownMenuEntries: const <DropdownMenuEntry<String>>[

DropdownMenuEntry(value: 'Aaniiih Nakoda College', label: 'Aaniiih Nakoda College'),
DropdownMenuEntry(value: 'Abcott Institute', label: 'Abcott Institute'),
DropdownMenuEntry(value: 'Abdullah Gul University', label: 'Abdullah Gul University'),
DropdownMenuEntry(value: 'Abertay University', label: 'Abertay University'),
DropdownMenuEntry(value: 'Aberystwyth University', label: 'Aberystwyth University'),
DropdownMenuEntry(value: 'Abilene Christian University', label: 'Abilene Christian University'),
DropdownMenuEntry(value: 'Abraham Baldwin Agricultural College', label: 'Abraham Baldwin Agricultural College'),
DropdownMenuEntry(value: 'Academia Serrant Inc', label: 'Academia Serrant Inc'),
DropdownMenuEntry(value: 'Academy College', label: 'Academy College'),
DropdownMenuEntry(value: 'Academy For Jewish Religion California', label: 'Academy For Jewish Religion California'),
DropdownMenuEntry(value: 'Academy For Nursing And Health Occupations', label: 'Academy For Nursing And Health Occupations'),
DropdownMenuEntry(value: 'Academy of Art University', label: 'Academy of Art University'),
DropdownMenuEntry(value: 'Academy Of Beauty Professionals Appleton', label: 'Academy Of Beauty Professionals Appleton'),
DropdownMenuEntry(value: 'Academy Of Beauty Professionals Green Bay', label: 'Academy Of Beauty Professionals Green Bay'),
DropdownMenuEntry(value: 'Academy Of Careers And Technology', label: 'Academy Of Careers And Technology'),
DropdownMenuEntry(value: 'Academy Of Chinese Culture And Health Sciences', label: 'Academy Of Chinese Culture And Health Sciences'),
DropdownMenuEntry(value: 'Academy Of Hair Design Lufkin', label: 'Academy Of Hair Design Lufkin'),
DropdownMenuEntry(value: 'Academy Of Hair Design Six', label: 'Academy Of Hair Design Six'),
DropdownMenuEntry(value: 'Academy Of Hair Design Springfield', label: 'Academy Of Hair Design Springfield'),
DropdownMenuEntry(value: 'Academy of Hair Technology', label: 'Academy of Hair Technology'),
DropdownMenuEntry(value: 'Academy Of Interactive Entertainment', label: 'Academy Of Interactive Entertainment'),
DropdownMenuEntry(value: 'Academy of Interactive Entertainment Lafayette', label: 'Academy of Interactive Entertainment Lafayette'),
DropdownMenuEntry(value: 'Academy Of Massage And Bodywork', label: 'Academy Of Massage And Bodywork'),
DropdownMenuEntry(value: 'Academy Of Professional Cosmetology', label: 'Academy Of Professional Cosmetology'),
DropdownMenuEntry(value: 'Academy Of Radio And Television Broadcasting', label: 'Academy Of Radio And Television Broadcasting'),
DropdownMenuEntry(value: 'Academy Of Salon Professionals', label: 'Academy Of Salon Professionals'),
DropdownMenuEntry(value: 'Academy Of Vocal Arts', label: 'Academy Of Vocal Arts'),
DropdownMenuEntry(value: 'Acaydia School Of Aesthetics', label: 'Acaydia School Of Aesthetics'),
DropdownMenuEntry(value: 'Ace Institute of Technology Manhattan', label: 'Ace Institute of Technology Manhattan'),
DropdownMenuEntry(value: 'Acupuncture And Massage College', label: 'Acupuncture And Massage College'),
DropdownMenuEntry(value: 'Ada University', label: 'Ada University'),
DropdownMenuEntry(value: 'Adams State University', label: 'Adams State University'),
DropdownMenuEntry(value: 'Adelphi University', label: 'Adelphi University'),
DropdownMenuEntry(value: 'Adrian College', label: 'Adrian College'),
DropdownMenuEntry(value: 'Advance Beauty Techs Academy', label: 'Advance Beauty Techs Academy'),
DropdownMenuEntry(value: 'Advanced Career Institute Visalia', label: 'Advanced Career Institute Visalia'),
DropdownMenuEntry(value: 'Advanced Technology Institute', label: 'Advanced Technology Institute'),
DropdownMenuEntry(value: 'Advantage Technical College', label: 'Advantage Technical College'),
DropdownMenuEntry(value: 'AdventHealth University', label: 'AdventHealth University'),
DropdownMenuEntry(value: 'Agnes Scott College', label: 'Agnes Scott College'),
DropdownMenuEntry(value: 'Ahmedabad University', label: 'Ahmedabad University'),
DropdownMenuEntry(value: 'Aiken School Of Cosmetology And Barbering', label: 'Aiken School Of Cosmetology And Barbering'),
DropdownMenuEntry(value: 'Aiken Technical College', label: 'Aiken Technical College'),
DropdownMenuEntry(value: 'Aims Community College', label: 'Aims Community College'),
DropdownMenuEntry(value: 'Al Akhawayn University', label: 'Al Akhawayn University'),
DropdownMenuEntry(value: 'Alabama Agricultural and Mechanical University', label: 'Alabama Agricultural and Mechanical University'),
DropdownMenuEntry(value: 'Alabama State University', label: 'Alabama State University'),
DropdownMenuEntry(value: 'Alamance Community College', label: 'Alamance Community College'),
DropdownMenuEntry(value: 'Alaska Bible College', label: 'Alaska Bible College'),
DropdownMenuEntry(value: 'Alaska Career College', label: 'Alaska Career College'),
DropdownMenuEntry(value: 'Alaska Pacific University', label: 'Alaska Pacific University'),
DropdownMenuEntry(value: 'Albany College of Pharmacy and Health Sciences', label: 'Albany College of Pharmacy and Health Sciences'),
DropdownMenuEntry(value: 'Albany State University', label: 'Albany State University'),
DropdownMenuEntry(value: 'Albany Technical College', label: 'Albany Technical College'),
DropdownMenuEntry(value: 'Albertus Magnus College', label: 'Albertus Magnus College'),
DropdownMenuEntry(value: 'Albion College', label: 'Albion College'),
DropdownMenuEntry(value: 'Albright College', label: 'Albright College'),
DropdownMenuEntry(value: 'Alcorn State University', label: 'Alcorn State University'),
DropdownMenuEntry(value: 'Alexander Paul Institute Of Hair Design', label: 'Alexander Paul Institute Of Hair Design'),
DropdownMenuEntry(value: 'Alexandria Technical and Community College', label: 'Alexandria Technical and Community College'),
DropdownMenuEntry(value: 'Alfred University', label: 'Alfred University'),
DropdownMenuEntry(value: 'Alhambra Medical University', label: 'Alhambra Medical University'),
DropdownMenuEntry(value: 'Alice Lloyd College', label: 'Alice Lloyd College'),
DropdownMenuEntry(value: 'All State Career School Pittsburgh', label: 'All State Career School Pittsburgh'),
DropdownMenuEntry(value: 'Allan Hancock College', label: 'Allan Hancock College'),
DropdownMenuEntry(value: 'Allegany College of Maryland', label: 'Allegany College of Maryland'),
DropdownMenuEntry(value: 'Allegheny College', label: 'Allegheny College'),
DropdownMenuEntry(value: 'Allegheny Wesleyan College', label: 'Allegheny Wesleyan College'),
DropdownMenuEntry(value: 'Allen County Community College', label: 'Allen County Community College'),
DropdownMenuEntry(value: 'Allen School of Health Sciences Brooklyn', label: 'Allen School of Health Sciences Brooklyn'),
DropdownMenuEntry(value: 'Allen School Of Health Sciences Phoenix', label: 'Allen School Of Health Sciences Phoenix'),
DropdownMenuEntry(value: 'Allen University', label: 'Allen University'),
DropdownMenuEntry(value: 'Alliance Computing Solutions Flushing', label: 'Alliance Computing Solutions Flushing'),
DropdownMenuEntry(value: 'Alliant International University', label: 'Alliant International University'),
DropdownMenuEntry(value: 'Allstate Hairstyling And Barber College', label: 'Allstate Hairstyling And Barber College'),
DropdownMenuEntry(value: 'Alma College', label: 'Alma College'),
DropdownMenuEntry(value: 'Alpena Community College', label: 'Alpena Community College'),
DropdownMenuEntry(value: 'Altoona Beauty School Inc', label: 'Altoona Beauty School Inc'),
DropdownMenuEntry(value: 'Alvernia University', label: 'Alvernia University'),
DropdownMenuEntry(value: 'Alverno College', label: 'Alverno College'),
DropdownMenuEntry(value: 'Alvin Community College', label: 'Alvin Community College'),
DropdownMenuEntry(value: 'Amarillo College', label: 'Amarillo College'),
DropdownMenuEntry(value: 'Amberton University', label: 'Amberton University'),
DropdownMenuEntry(value: 'American Academy McAllister Institute of Funeral Service', label: 'American Academy McAllister Institute of Funeral Service'),
DropdownMenuEntry(value: 'American Academy Of Cosmetology', label: 'American Academy Of Cosmetology'),
DropdownMenuEntry(value: 'American Academy of Dramatic Arts', label: 'American Academy of Dramatic Arts'),
DropdownMenuEntry(value: 'American Academy Of Health And Wellness', label: 'American Academy Of Health And Wellness'),
DropdownMenuEntry(value: 'American Baptist College', label: 'American Baptist College'),
DropdownMenuEntry(value: 'American Beauty Academy Salt Lake', label: 'American Beauty Academy Salt Lake'),
DropdownMenuEntry(value: 'American Beauty College West Covina', label: 'American Beauty College West Covina'),
DropdownMenuEntry(value: 'American Beauty Schools', label: 'American Beauty Schools'),
DropdownMenuEntry(value: 'American Career College Ontario', label: 'American Career College Ontario'),
DropdownMenuEntry(value: 'American Career College Orange County', label: 'American Career College Orange County'),
DropdownMenuEntry(value: 'American College Dublin', label: 'American College Dublin'),
DropdownMenuEntry(value: 'American Hair Academy', label: 'American Hair Academy'),
DropdownMenuEntry(value: 'American Institute Of Beauty', label: 'American Institute Of Beauty'),
DropdownMenuEntry(value: 'American Institute Of Medical Technology', label: 'American Institute Of Medical Technology'),
DropdownMenuEntry(value: 'American InterContinental University', label: 'American InterContinental University'),
DropdownMenuEntry(value: 'American InterContinental University Atlanta', label: 'American InterContinental University Atlanta'),
DropdownMenuEntry(value: 'American International College', label: 'American International College'),
DropdownMenuEntry(value: 'American Massage And Bodywork Institute', label: 'American Massage And Bodywork Institute'),
DropdownMenuEntry(value: 'American Medical Academy', label: 'American Medical Academy'),
DropdownMenuEntry(value: 'American National University Louisville', label: 'American National University Louisville'),
DropdownMenuEntry(value: 'American National University Nashville', label: 'American National University Nashville'),
DropdownMenuEntry(value: 'American National University Pikeville', label: 'American National University Pikeville'),
DropdownMenuEntry(value: 'American River College', label: 'American River College'),
DropdownMenuEntry(value: 'American Samoa Community College', label: 'American Samoa Community College'),
DropdownMenuEntry(value: 'American Sentinel College Of Nursing And Health Sciences At Post University', label: 'American Sentinel College Of Nursing And Health Sciences At Post University'),
DropdownMenuEntry(value: 'American University', label: 'American University'),
DropdownMenuEntry(value: 'American University in Bulgaria', label: 'American University in Bulgaria'),
DropdownMenuEntry(value: 'American University in Cairo', label: 'American University in Cairo'),
DropdownMenuEntry(value: 'American University in Dubai', label: 'American University in Dubai'),
DropdownMenuEntry(value: 'American University of Afghanistan', label: 'American University of Afghanistan'),
DropdownMenuEntry(value: 'American University Of Armenia', label: 'American University Of Armenia'),
DropdownMenuEntry(value: 'American University of Beirut', label: 'American University of Beirut'),
DropdownMenuEntry(value: 'American University of Kuwait', label: 'American University of Kuwait'),
DropdownMenuEntry(value: 'American University of Myanmar', label: 'American University of Myanmar'),
DropdownMenuEntry(value: 'American University of Paris', label: 'American University of Paris'),
DropdownMenuEntry(value: 'American University Of Puerto Rico Manati', label: 'American University Of Puerto Rico Manati'),
DropdownMenuEntry(value: 'American University of Rome', label: 'American University of Rome'),
DropdownMenuEntry(value: 'American University of Sharjah', label: 'American University of Sharjah'),
DropdownMenuEntry(value: 'American University of Technology: Lebanon', label: 'American University of Technology: Lebanon'),
DropdownMenuEntry(value: 'American University of the Caribbean School of Medicine', label: 'American University of the Caribbean School of Medicine'),
DropdownMenuEntry(value: 'Amherst College', label: 'Amherst College'),
DropdownMenuEntry(value: 'Amridge University', label: 'Amridge University'),
DropdownMenuEntry(value: 'Anant National University Sanskardham Campus', label: 'Anant National University Sanskardham Campus'),
DropdownMenuEntry(value: 'Anderson University (Anderson, IN)', label: 'Anderson University (Anderson, IN)'),
DropdownMenuEntry(value: 'Anderson University (Anderson, SC)', label: 'Anderson University (Anderson, SC)'),
DropdownMenuEntry(value: 'Andrew College', label: 'Andrew College'),
DropdownMenuEntry(value: 'Andrews University', label: 'Andrews University'),
DropdownMenuEntry(value: 'Angeles College', label: 'Angeles College'),
DropdownMenuEntry(value: 'Angelina College', label: 'Angelina College'),
DropdownMenuEntry(value: 'Angelo State University', label: 'Angelo State University'),
DropdownMenuEntry(value: 'Anglia Ruskin University', label: 'Anglia Ruskin University'),
DropdownMenuEntry(value: 'Ann Webb Skin Institute', label: 'Ann Webb Skin Institute'),
DropdownMenuEntry(value: 'Anna Maria College', label: 'Anna Maria College'),
DropdownMenuEntry(value: 'Anne Arundel Community College', label: 'Anne Arundel Community College'),
DropdownMenuEntry(value: 'Anoka Technical College', label: 'Anoka Technical College'),
DropdownMenuEntry(value: 'Anoka-Ramsey Community College', label: 'Anoka-Ramsey Community College'),
DropdownMenuEntry(value: 'Another Level Barbering And Cosmetology School', label: 'Another Level Barbering And Cosmetology School'),
DropdownMenuEntry(value: 'Antelope Valley College', label: 'Antelope Valley College'),
DropdownMenuEntry(value: 'Antioch College', label: 'Antioch College'),
DropdownMenuEntry(value: 'Antioch University Los Angeles', label: 'Antioch University Los Angeles'),
DropdownMenuEntry(value: 'Antioch University Santa Barbara', label: 'Antioch University Santa Barbara'),
DropdownMenuEntry(value: 'Appalachian Bible College', label: 'Appalachian Bible College'),
DropdownMenuEntry(value: 'Appalachian State University', label: 'Appalachian State University'),
DropdownMenuEntry(value: 'Applied Technology Services', label: 'Applied Technology Services'),
DropdownMenuEntry(value: 'Aquinas College', label: 'Aquinas College'),
DropdownMenuEntry(value: 'Arapahoe Community College', label: 'Arapahoe Community College'),
DropdownMenuEntry(value: 'Arcadia University', label: 'Arcadia University'),
DropdownMenuEntry(value: 'Arizona Academy Of Beauty', label: 'Arizona Academy Of Beauty'),
DropdownMenuEntry(value: 'Arizona Christian University', label: 'Arizona Christian University'),
DropdownMenuEntry(value: 'Arizona College Glendale', label: 'Arizona College Glendale'),
DropdownMenuEntry(value: 'Arizona College Mesa', label: 'Arizona College Mesa'),
DropdownMenuEntry(value: 'Arizona School Of Acupuncture And Oriental Medicine', label: 'Arizona School Of Acupuncture And Oriental Medicine'),
DropdownMenuEntry(value: 'Arizona State University', label: 'Arizona State University'),
DropdownMenuEntry(value: 'Arizona State University Downtown Phoenix', label: 'Arizona State University Downtown Phoenix'),
DropdownMenuEntry(value: 'Arizona Western College', label: 'Arizona Western College'),
DropdownMenuEntry(value: 'Arkansas Baptist College', label: 'Arkansas Baptist College'),
DropdownMenuEntry(value: 'Arkansas Beauty College', label: 'Arkansas Beauty College'),
DropdownMenuEntry(value: 'Arkansas Northeastern College', label: 'Arkansas Northeastern College'),
DropdownMenuEntry(value: 'Arkansas State University', label: 'Arkansas State University'),
DropdownMenuEntry(value: 'Arkansas State University Mid-South', label: 'Arkansas State University Mid-South'),
DropdownMenuEntry(value: 'Arkansas State University Three Rivers', label: 'Arkansas State University Three Rivers'),
DropdownMenuEntry(value: 'Arkansas State University: Beebe', label: 'Arkansas State University: Beebe'),
DropdownMenuEntry(value: 'Arkansas State University: Mountain Home', label: 'Arkansas State University: Mountain Home'),
DropdownMenuEntry(value: 'Arkansas State University: Newport', label: 'Arkansas State University: Newport'),
DropdownMenuEntry(value: 'Arkansas Tech University', label: 'Arkansas Tech University'),
DropdownMenuEntry(value: 'Arkansas Technical School', label: 'Arkansas Technical School'),
DropdownMenuEntry(value: 'Arlington Baptist University', label: 'Arlington Baptist University'),
DropdownMenuEntry(value: 'Arlington Career Institute', label: 'Arlington Career Institute'),
DropdownMenuEntry(value: 'Art Academy of Cincinnati', label: 'Art Academy of Cincinnati'),
DropdownMenuEntry(value: 'Art Center College of Design', label: 'Art Center College of Design'),
DropdownMenuEntry(value: 'Arthurs Beauty College Conway', label: 'Arthurs Beauty College Conway'),
DropdownMenuEntry(value: 'Arthurs Beauty College Jonesboro', label: 'Arthurs Beauty College Jonesboro'),
DropdownMenuEntry(value: 'Artistic Nails And Beauty Academy Lakeland', label: 'Artistic Nails And Beauty Academy Lakeland'),
DropdownMenuEntry(value: 'Arts Science & Technology University in Lebanon', label: 'Arts Science & Technology University in Lebanon'),
DropdownMenuEntry(value: 'Arts University Bournemouth', label: 'Arts University Bournemouth'),
DropdownMenuEntry(value: 'Asbury University', label: 'Asbury University'),
DropdownMenuEntry(value: 'Asher Institute Of Hampton', label: 'Asher Institute Of Hampton'),
DropdownMenuEntry(value: 'Asheville-Buncombe Technical Community College', label: 'Asheville-Buncombe Technical Community College'),
DropdownMenuEntry(value: 'Ashland Community And Technical College', label: 'Ashland Community And Technical College'),
DropdownMenuEntry(value: 'Ashland County West Holmes Career Center', label: 'Ashland County West Holmes Career Center'),
DropdownMenuEntry(value: 'Ashland University', label: 'Ashland University'),
DropdownMenuEntry(value: 'Ashoka University', label: 'Ashoka University'),
DropdownMenuEntry(value: 'Ashworth College', label: 'Ashworth College'),
DropdownMenuEntry(value: 'ASI Career Institute', label: 'ASI Career Institute'),
DropdownMenuEntry(value: 'Aspen University', label: 'Aspen University'),
DropdownMenuEntry(value: 'ASPIRA City College', label: 'ASPIRA City College'),
DropdownMenuEntry(value: 'Associated Barber College Of San Diego', label: 'Associated Barber College Of San Diego'),
DropdownMenuEntry(value: 'Associated Technical College Los Angeles', label: 'Associated Technical College Los Angeles'),
DropdownMenuEntry(value: 'Associated Technical College San Diego', label: 'Associated Technical College San Diego'),
DropdownMenuEntry(value: 'Assumption College for Sisters', label: 'Assumption College for Sisters'),
DropdownMenuEntry(value: 'Assumption University', label: 'Assumption University'),
DropdownMenuEntry(value: 'ATA College Cincinnati', label: 'ATA College Cincinnati'),
DropdownMenuEntry(value: 'Atelier Esthetique Institute of Esthetics', label: 'Atelier Esthetique Institute of Esthetics'),
DropdownMenuEntry(value: 'Atenas College', label: 'Atenas College'),
DropdownMenuEntry(value: 'Athens State University', label: 'Athens State University'),
DropdownMenuEntry(value: 'Athens Technical College', label: 'Athens Technical College'),
DropdownMenuEntry(value: 'Atlanta Metropolitan State College', label: 'Atlanta Metropolitan State College'),
DropdownMenuEntry(value: 'Atlanta School Of Massage', label: 'Atlanta School Of Massage'),
DropdownMenuEntry(value: 'Atlanta Technical College', label: 'Atlanta Technical College'),
DropdownMenuEntry(value: 'Atlantic Cape Community College', label: 'Atlantic Cape Community College'),
DropdownMenuEntry(value: 'Atlantic Institute Of Oriental Medicine', label: 'Atlantic Institute Of Oriental Medicine'),
DropdownMenuEntry(value: 'Atlantic University College', label: 'Atlantic University College'),
DropdownMenuEntry(value: 'Atlantis University', label: 'Atlantis University'),
DropdownMenuEntry(value: 'Atria University', label: 'Atria University'),
DropdownMenuEntry(value: 'Auburn University', label: 'Auburn University'),
DropdownMenuEntry(value: 'Auburn University at Montgomery', label: 'Auburn University at Montgomery'),
DropdownMenuEntry(value: 'Augsburg University', label: 'Augsburg University'),
DropdownMenuEntry(value: 'Augusta Technical College', label: 'Augusta Technical College'),
DropdownMenuEntry(value: 'Augusta University', label: 'Augusta University'),
DropdownMenuEntry(value: 'Augustana College', label: 'Augustana College'),
DropdownMenuEntry(value: 'Augustana University', label: 'Augustana University'),
DropdownMenuEntry(value: 'Auguste Escoffier School Of Culinary Arts Austin', label: 'Auguste Escoffier School Of Culinary Arts Austin'),
DropdownMenuEntry(value: 'Aultman College of Nursing and Health Sciences', label: 'Aultman College of Nursing and Health Sciences'),
DropdownMenuEntry(value: 'Aurora University', label: 'Aurora University'),
DropdownMenuEntry(value: 'Austin College', label: 'Austin College'),
DropdownMenuEntry(value: 'Austin Community College', label: 'Austin Community College'),
DropdownMenuEntry(value: 'Austin Kade Academy', label: 'Austin Kade Academy'),
DropdownMenuEntry(value: 'Austin Peay State University', label: 'Austin Peay State University'),
DropdownMenuEntry(value: 'Austins Beauty College', label: 'Austins Beauty College'),
DropdownMenuEntry(value: 'Avalon Institute Aurora', label: 'Avalon Institute Aurora'),
DropdownMenuEntry(value: 'Avalon Institute Layton', label: 'Avalon Institute Layton'),
DropdownMenuEntry(value: 'Avalon Institute Mesa', label: 'Avalon Institute Mesa'),
DropdownMenuEntry(value: 'Ave Maria University', label: 'Ave Maria University'),
DropdownMenuEntry(value: 'Aveda Arts & Sciences Institute Baton Rouge', label: 'Aveda Arts & Sciences Institute Baton Rouge'),
DropdownMenuEntry(value: 'Aveda Arts & Sciences Institute Lafayette', label: 'Aveda Arts & Sciences Institute Lafayette'),
DropdownMenuEntry(value: 'Aveda Arts & Sciences Institute New York', label: 'Aveda Arts & Sciences Institute New York'),
DropdownMenuEntry(value: 'Aveda Arts And Sciences Institute Seattle', label: 'Aveda Arts And Sciences Institute Seattle'),
DropdownMenuEntry(value: 'Aveda Fredric\'s Institute Indianapolis', label: 'Aveda Fredric\'s Institute Indianapolis'),
DropdownMenuEntry(value: 'Aveda Fredrics Institute Cincinnati', label: 'Aveda Fredrics Institute Cincinnati'),
DropdownMenuEntry(value: 'Aveda Institute Boise', label: 'Aveda Institute Boise'),
DropdownMenuEntry(value: 'Aveda Institute Chapel Hill', label: 'Aveda Institute Chapel Hill'),
DropdownMenuEntry(value: 'Aveda Institute Columbus', label: 'Aveda Institute Columbus'),
DropdownMenuEntry(value: 'Aveda Institute Denver', label: 'Aveda Institute Denver'),
DropdownMenuEntry(value: 'Aveda Institute Des Moines', label: 'Aveda Institute Des Moines'),
DropdownMenuEntry(value: 'Aveda Institute Fort Myers', label: 'Aveda Institute Fort Myers'),
DropdownMenuEntry(value: 'Aveda Institute Las Vegas', label: 'Aveda Institute Las Vegas'),
DropdownMenuEntry(value: 'Aveda Institute Phoenix', label: 'Aveda Institute Phoenix'),
DropdownMenuEntry(value: 'Aveda Institute Portland', label: 'Aveda Institute Portland'),
DropdownMenuEntry(value: 'Aveda Institute Portland Vancouver', label: 'Aveda Institute Portland Vancouver'),
DropdownMenuEntry(value: 'Aveda Institute Provo', label: 'Aveda Institute Provo'),
DropdownMenuEntry(value: 'Aveda Institute South Florida', label: 'Aveda Institute South Florida'),
DropdownMenuEntry(value: 'Aveda Institute Tallahassee', label: 'Aveda Institute Tallahassee'),
DropdownMenuEntry(value: 'Aveda Institute Twin Falls', label: 'Aveda Institute Twin Falls'),
DropdownMenuEntry(value: 'Avenue Academy A Cosmetology Institute', label: 'Avenue Academy A Cosmetology Institute'),
DropdownMenuEntry(value: 'Avenue Five Institute-South Austin Campus', label: 'Avenue Five Institute-South Austin Campus'),
DropdownMenuEntry(value: 'Avera McKennan School Of Radiologic Technology', label: 'Avera McKennan School Of Radiologic Technology'),
DropdownMenuEntry(value: 'Avera Sacred Heart Hospital School Of Radiologic Technology', label: 'Avera Sacred Heart Hospital School Of Radiologic Technology'),
DropdownMenuEntry(value: 'Averett University', label: 'Averett University'),
DropdownMenuEntry(value: 'Avery James College', label: 'Avery James College'),
DropdownMenuEntry(value: 'Aviation Institute Of Maintenance Atlanta', label: 'Aviation Institute Of Maintenance Atlanta'),
DropdownMenuEntry(value: 'Aviation Institute Of Maintenance Charlotte', label: 'Aviation Institute Of Maintenance Charlotte'),
DropdownMenuEntry(value: 'Aviation Institute Of Maintenance Dallas', label: 'Aviation Institute Of Maintenance Dallas'),
DropdownMenuEntry(value: 'Aviation Institute Of Maintenance Fremont', label: 'Aviation Institute Of Maintenance Fremont'),
DropdownMenuEntry(value: 'Aviation Institute of Maintenance Las Vegas', label: 'Aviation Institute of Maintenance Las Vegas'),
DropdownMenuEntry(value: 'Aviation Institute Of Maintenance Manassas', label: 'Aviation Institute Of Maintenance Manassas'),
DropdownMenuEntry(value: 'Aviation Institute Of Maintenance Orlando Metro', label: 'Aviation Institute Of Maintenance Orlando Metro'),
DropdownMenuEntry(value: 'Aviation Institute Of Maintenance Teterboro', label: 'Aviation Institute Of Maintenance Teterboro'),
DropdownMenuEntry(value: 'Avila University', label: 'Avila University'),
DropdownMenuEntry(value: 'Award Beauty School', label: 'Award Beauty School'),
DropdownMenuEntry(value: 'Ayers Career College', label: 'Ayers Career College'),
DropdownMenuEntry(value: 'Azim Premji University', label: 'Azim Premji University'),
DropdownMenuEntry(value: 'Azusa Pacific University', label: 'Azusa Pacific University'),
DropdownMenuEntry(value: 'B Unique Beauty And Barber Academy', label: 'B Unique Beauty And Barber Academy'),
DropdownMenuEntry(value: 'Babson College', label: 'Babson College'),
DropdownMenuEntry(value: 'Bahamas Agriculture And Marine Science Institute', label: 'Bahamas Agriculture And Marine Science Institute'),
DropdownMenuEntry(value: 'Bais Binyomin Academy', label: 'Bais Binyomin Academy'),
DropdownMenuEntry(value: 'Bais Medrash Zichron Meir', label: 'Bais Medrash Zichron Meir'),
DropdownMenuEntry(value: 'Baker College', label: 'Baker College'),
DropdownMenuEntry(value: 'Baker University', label: 'Baker University'),
DropdownMenuEntry(value: 'Bakersfield College', label: 'Bakersfield College'),
DropdownMenuEntry(value: 'Bakke Graduate University', label: 'Bakke Graduate University'),
DropdownMenuEntry(value: 'Baldwin Beauty School-South Austin', label: 'Baldwin Beauty School-South Austin'),
DropdownMenuEntry(value: 'Baldwin Wallace University', label: 'Baldwin Wallace University'),
DropdownMenuEntry(value: 'Ball State University', label: 'Ball State University'),
DropdownMenuEntry(value: 'Baltimore City Community College', label: 'Baltimore City Community College'),
DropdownMenuEntry(value: 'Baltimore Studio Of Hair Design', label: 'Baltimore Studio Of Hair Design'),
DropdownMenuEntry(value: 'Bangor University', label: 'Bangor University'),
DropdownMenuEntry(value: 'Baptist College of Florida', label: 'Baptist College of Florida'),
DropdownMenuEntry(value: 'Baptist Health Sciences University', label: 'Baptist Health Sciences University'),
DropdownMenuEntry(value: 'Baptist Missionary Association Theological Seminary', label: 'Baptist Missionary Association Theological Seminary'),
DropdownMenuEntry(value: 'Baptist University of the Americas', label: 'Baptist University of the Americas'),
DropdownMenuEntry(value: 'Barber Institute Of Texas Longview', label: 'Barber Institute Of Texas Longview'),
DropdownMenuEntry(value: 'Barber School Of Pittsburgh', label: 'Barber School Of Pittsburgh'),
DropdownMenuEntry(value: 'Barber Tech Academy', label: 'Barber Tech Academy'),
DropdownMenuEntry(value: 'Barclay College', label: 'Barclay College'),
DropdownMenuEntry(value: 'Bard College', label: 'Bard College'),
DropdownMenuEntry(value: 'Bard College at Simon\'s Rock', label: 'Bard College at Simon\'s Rock'),
DropdownMenuEntry(value: 'Bard College Berlin', label: 'Bard College Berlin'),
DropdownMenuEntry(value: 'Barnard College', label: 'Barnard College'),
DropdownMenuEntry(value: 'Barry University', label: 'Barry University'),
DropdownMenuEntry(value: 'Barstow Community College', label: 'Barstow Community College'),
DropdownMenuEntry(value: 'Barton College', label: 'Barton College'),
DropdownMenuEntry(value: 'Barton County Community College', label: 'Barton County Community College'),
DropdownMenuEntry(value: 'Bastyr University', label: 'Bastyr University'),
DropdownMenuEntry(value: 'Bates College', label: 'Bates College'),
DropdownMenuEntry(value: 'Bates Technical College', label: 'Bates Technical College'),
DropdownMenuEntry(value: 'Bath Spa University Newton Park', label: 'Bath Spa University Newton Park'),
DropdownMenuEntry(value: 'Baton Rouge Community College', label: 'Baton Rouge Community College'),
DropdownMenuEntry(value: 'Baton Rouge School of Computers', label: 'Baton Rouge School of Computers'),
DropdownMenuEntry(value: 'Bay Area Medical Academy', label: 'Bay Area Medical Academy'),
DropdownMenuEntry(value: 'Bay Atlantic University', label: 'Bay Atlantic University'),
DropdownMenuEntry(value: 'Bay De Noc Community College', label: 'Bay De Noc Community College'),
DropdownMenuEntry(value: 'Bay Mills Community College', label: 'Bay Mills Community College'),
DropdownMenuEntry(value: 'Bay Path University', label: 'Bay Path University'),
DropdownMenuEntry(value: 'Baylor University', label: 'Baylor University'),
DropdownMenuEntry(value: 'Beacon College', label: 'Beacon College'),
DropdownMenuEntry(value: 'Beal University', label: 'Beal University'),
DropdownMenuEntry(value: 'Beau Monde Academy Of Barbering And Cosmetology', label: 'Beau Monde Academy Of Barbering And Cosmetology'),
DropdownMenuEntry(value: 'Beaufort County Community College', label: 'Beaufort County Community College'),
DropdownMenuEntry(value: 'Beauty Institute', label: 'Beauty Institute'),
DropdownMenuEntry(value: 'Beauty Institute Allentown', label: 'Beauty Institute Allentown'),
DropdownMenuEntry(value: 'Beaver Falls Beauty Academy', label: 'Beaver Falls Beauty Academy'),
DropdownMenuEntry(value: 'Beckfield College', label: 'Beckfield College'),
DropdownMenuEntry(value: 'Bel-Rea Institute of Animal Technology', label: 'Bel-Rea Institute of Animal Technology'),
DropdownMenuEntry(value: 'Belhaven University', label: 'Belhaven University'),
DropdownMenuEntry(value: 'Bell Mar Beauty College', label: 'Bell Mar Beauty College'),
DropdownMenuEntry(value: 'Bella Capelli Academy', label: 'Bella Capelli Academy'),
DropdownMenuEntry(value: 'Bellarmine University', label: 'Bellarmine University'),
DropdownMenuEntry(value: 'Bellevue College', label: 'Bellevue College'),
DropdownMenuEntry(value: 'Bellevue University', label: 'Bellevue University'),
DropdownMenuEntry(value: 'Bellin College', label: 'Bellin College'),
DropdownMenuEntry(value: 'Bellingham Technical College', label: 'Bellingham Technical College'),
DropdownMenuEntry(value: 'Bellus Academy Kansas', label: 'Bellus Academy Kansas'),
DropdownMenuEntry(value: 'Belmont Abbey College', label: 'Belmont Abbey College'),
DropdownMenuEntry(value: 'Belmont College', label: 'Belmont College'),
DropdownMenuEntry(value: 'Belmont University', label: 'Belmont University'),
DropdownMenuEntry(value: 'Beloit College', label: 'Beloit College'),
DropdownMenuEntry(value: 'Bemidji State University', label: 'Bemidji State University'),
DropdownMenuEntry(value: 'Benedict College', label: 'Benedict College'),
DropdownMenuEntry(value: 'Benedictine College', label: 'Benedictine College'),
DropdownMenuEntry(value: 'Benedictine University', label: 'Benedictine University'),
DropdownMenuEntry(value: 'Benjamin Franklin Cummings Institute Of Technology', label: 'Benjamin Franklin Cummings Institute Of Technology'),
DropdownMenuEntry(value: 'Bennett Career Institute', label: 'Bennett Career Institute'),
DropdownMenuEntry(value: 'Bennett College', label: 'Bennett College'),
DropdownMenuEntry(value: 'Bennett University', label: 'Bennett University'),
DropdownMenuEntry(value: 'Bennington College', label: 'Bennington College'),
DropdownMenuEntry(value: 'Bentley University', label: 'Bentley University'),
DropdownMenuEntry(value: 'Berea College', label: 'Berea College'),
DropdownMenuEntry(value: 'Bergen Community College', label: 'Bergen Community College'),
DropdownMenuEntry(value: 'Bergin University of Canine Studies', label: 'Bergin University of Canine Studies'),
DropdownMenuEntry(value: 'Berkeley City College', label: 'Berkeley City College'),
DropdownMenuEntry(value: 'Berkeley College', label: 'Berkeley College'),
DropdownMenuEntry(value: 'Berkeley College of New York City', label: 'Berkeley College of New York City'),
DropdownMenuEntry(value: 'Berklee College of Music', label: 'Berklee College of Music'),
DropdownMenuEntry(value: 'Berkowits School of Electrolysis', label: 'Berkowits School of Electrolysis'),
DropdownMenuEntry(value: 'Berks Technical Institute', label: 'Berks Technical Institute'),
DropdownMenuEntry(value: 'Berkshire Community College', label: 'Berkshire Community College'),
DropdownMenuEntry(value: 'Bermuda College', label: 'Bermuda College'),
DropdownMenuEntry(value: 'Berry College', label: 'Berry College'),
DropdownMenuEntry(value: 'Bet Medrash Gadol Ateret Torah', label: 'Bet Medrash Gadol Ateret Torah'),
DropdownMenuEntry(value: 'Beth Medrash Meor Yitzchok', label: 'Beth Medrash Meor Yitzchok'),
DropdownMenuEntry(value: 'Bethany College (Bethany, WV)', label: 'Bethany College (Bethany, WV)'),
DropdownMenuEntry(value: 'Bethany College (Lindsborg, KS)', label: 'Bethany College (Lindsborg, KS)'),
DropdownMenuEntry(value: 'Bethany Global University', label: 'Bethany Global University'),
DropdownMenuEntry(value: 'Bethany Lutheran College', label: 'Bethany Lutheran College'),
DropdownMenuEntry(value: 'Bethel College', label: 'Bethel College'),
DropdownMenuEntry(value: 'Bethel University (Mc Kenzie, TN)', label: 'Bethel University (Mc Kenzie, TN)'),
DropdownMenuEntry(value: 'Bethel University (Mishawaka, IN)', label: 'Bethel University (Mishawaka, IN)'),
DropdownMenuEntry(value: 'Bethel University (Saint Paul, MN)', label: 'Bethel University (Saint Paul, MN)'),
DropdownMenuEntry(value: 'Bethesda University', label: 'Bethesda University'),
DropdownMenuEntry(value: 'Bethune-Cookman University', label: 'Bethune-Cookman University'),
DropdownMenuEntry(value: 'Beverly Hills Design Institute', label: 'Beverly Hills Design Institute'),
DropdownMenuEntry(value: 'Bevill State Community College', label: 'Bevill State Community College'),
DropdownMenuEntry(value: 'Beyond 21st Century Beauty Academy', label: 'Beyond 21st Century Beauty Academy'),
DropdownMenuEntry(value: 'Bidwell Training Center', label: 'Bidwell Training Center'),
DropdownMenuEntry(value: 'Big Bend Community College', label: 'Big Bend Community College'),
DropdownMenuEntry(value: 'Big Sandy Community and Technical College', label: 'Big Sandy Community and Technical College'),
DropdownMenuEntry(value: 'Biola University', label: 'Biola University'),
DropdownMenuEntry(value: 'Birzeit University', label: 'Birzeit University'),
DropdownMenuEntry(value: 'Bishop State Community College', label: 'Bishop State Community College'),
DropdownMenuEntry(value: 'Bishop\'s University', label: 'Bishop\'s University'),
DropdownMenuEntry(value: 'Bismarck State College', label: 'Bismarck State College'),
DropdownMenuEntry(value: 'BJs Beauty And Barber College', label: 'BJs Beauty And Barber College'),
DropdownMenuEntry(value: 'BK Cosmo College Of Cosmetology', label: 'BK Cosmo College Of Cosmetology'),
DropdownMenuEntry(value: 'Black Hawk College', label: 'Black Hawk College'),
DropdownMenuEntry(value: 'Black Hills State University', label: 'Black Hills State University'),
DropdownMenuEntry(value: 'Black River Technical College', label: 'Black River Technical College'),
DropdownMenuEntry(value: 'Blackburn College', label: 'Blackburn College'),
DropdownMenuEntry(value: 'Blackfeet Community College', label: 'Blackfeet Community College'),
DropdownMenuEntry(value: 'Blackhawk Technical College', label: 'Blackhawk Technical College'),
DropdownMenuEntry(value: 'Bladen Community College', label: 'Bladen Community College'),
DropdownMenuEntry(value: 'Blalock\'s Professional Beauty College', label: 'Blalock\'s Professional Beauty College'),
DropdownMenuEntry(value: 'Blessing-Rieman College of Nursing & Health Sciences', label: 'Blessing-Rieman College of Nursing & Health Sciences'),
DropdownMenuEntry(value: 'Blinn College', label: 'Blinn College'),
DropdownMenuEntry(value: 'Bloomfield College Of Montclair State University', label: 'Bloomfield College Of Montclair State University'),
DropdownMenuEntry(value: 'Blue Cliff College Alexandria', label: 'Blue Cliff College Alexandria'),
DropdownMenuEntry(value: 'Blue Mountain Christian University', label: 'Blue Mountain Christian University'),
DropdownMenuEntry(value: 'Blue Mountain Community College', label: 'Blue Mountain Community College'),
DropdownMenuEntry(value: 'Blue Ridge Community and Technical College', label: 'Blue Ridge Community and Technical College'),
DropdownMenuEntry(value: 'Blue Ridge Community College (Flat Rock, NC)', label: 'Blue Ridge Community College (Flat Rock, NC)'),
DropdownMenuEntry(value: 'Blue Ridge Community College (Weyers Cave, VA)', label: 'Blue Ridge Community College (Weyers Cave, VA)'),
DropdownMenuEntry(value: 'Bluefield State University', label: 'Bluefield State University'),
DropdownMenuEntry(value: 'Bluefield University', label: 'Bluefield University'),
DropdownMenuEntry(value: 'Bluegrass Community and Technical College', label: 'Bluegrass Community and Technical College'),
DropdownMenuEntry(value: 'Bluffton University', label: 'Bluffton University'),
DropdownMenuEntry(value: 'Bnos Zion Of Bobov Seminary', label: 'Bnos Zion Of Bobov Seminary'),
DropdownMenuEntry(value: 'Board of Cooperative Educational Services Eastern Suffolk', label: 'Board of Cooperative Educational Services Eastern Suffolk'),
DropdownMenuEntry(value: 'Board of Cooperative Educational Services Eastern Suffolk Brentwood', label: 'Board of Cooperative Educational Services Eastern Suffolk Brentwood'),
DropdownMenuEntry(value: 'Board Of Cooperative Educational Services Monroe 2 Orleans', label: 'Board Of Cooperative Educational Services Monroe 2 Orleans'),
DropdownMenuEntry(value: 'Board of Cooperative Educational Services Onondaga Cortland Madison', label: 'Board of Cooperative Educational Services Onondaga Cortland Madison'),
DropdownMenuEntry(value: 'Bob Jones University', label: 'Bob Jones University'),
DropdownMenuEntry(value: 'Boca Beauty Academy', label: 'Boca Beauty Academy'),
DropdownMenuEntry(value: 'Bocconi University', label: 'Bocconi University'),
DropdownMenuEntry(value: 'Boise Barber College', label: 'Boise Barber College'),
DropdownMenuEntry(value: 'Boise Bible College', label: 'Boise Bible College'),
DropdownMenuEntry(value: 'Boise State University', label: 'Boise State University'),
DropdownMenuEntry(value: 'Bolivar Technical', label: 'Bolivar Technical'),
DropdownMenuEntry(value: 'Colorado State University: Pueblo', label: 'Colorado State University: Pueblo'),
DropdownMenuEntry(value: 'Colorado Technical University', label: 'Colorado Technical University'),
DropdownMenuEntry(value: 'Columbia Basin College', label: 'Columbia Basin College'),
DropdownMenuEntry(value: 'Columbia Central University: Caguas', label: 'Columbia Central University: Caguas'),
DropdownMenuEntry(value: 'Columbia Central University: Yauco', label: 'Columbia Central University: Yauco'),
DropdownMenuEntry(value: 'Columbia College (Columbia, MO)', label: 'Columbia College (Columbia, MO)'),
DropdownMenuEntry(value: 'Columbia College (Columbia, SC)', label: 'Columbia College (Columbia, SC)'),
DropdownMenuEntry(value: 'Columbia College (Sonora, CA)', label: 'Columbia College (Sonora, CA)'),
DropdownMenuEntry(value: 'Columbia College Chicago', label: 'Columbia College Chicago'),
DropdownMenuEntry(value: 'Columbia College Hollywood', label: 'Columbia College Hollywood'),
DropdownMenuEntry(value: 'Columbia International University', label: 'Columbia International University'),
DropdownMenuEntry(value: 'Columbia Southern University', label: 'Columbia Southern University'),
DropdownMenuEntry(value: 'Columbia State Community College', label: 'Columbia State Community College'),
DropdownMenuEntry(value: 'Columbia University', label: 'Columbia University'),
DropdownMenuEntry(value: 'Columbia University: School of General Studies', label: 'Columbia University: School of General Studies'),
DropdownMenuEntry(value: 'Columbia-Greene Community College', label: 'Columbia-Greene Community College'),
DropdownMenuEntry(value: 'Columbus College of Art and Design', label: 'Columbus College of Art and Design'),
DropdownMenuEntry(value: 'Columbus State Community College Columbus Campus', label: 'Columbus State Community College Columbus Campus'),
DropdownMenuEntry(value: 'Columbus State University', label: 'Columbus State University'),
DropdownMenuEntry(value: 'Columbus Technical College', label: 'Columbus Technical College'),
DropdownMenuEntry(value: 'Commonwealth Institute of Funeral Service', label: 'Commonwealth Institute of Funeral Service'),
DropdownMenuEntry(value: 'Commonwealth Technical Institute', label: 'Commonwealth Technical Institute'),
DropdownMenuEntry(value: 'Commonwealth University Of Pennsylvania', label: 'Commonwealth University Of Pennsylvania'),
DropdownMenuEntry(value: 'Commonwealth University Of Pennsylvania Lock Haven', label: 'Commonwealth University Of Pennsylvania Lock Haven'),
DropdownMenuEntry(value: 'Commonwealth University Of Pennsylvania Mansfield', label: 'Commonwealth University Of Pennsylvania Mansfield'),
DropdownMenuEntry(value: 'Community College of Allegheny County', label: 'Community College of Allegheny County'),
DropdownMenuEntry(value: 'Community College of Aurora', label: 'Community College of Aurora'),
DropdownMenuEntry(value: 'Community College of Baltimore County', label: 'Community College of Baltimore County'),
DropdownMenuEntry(value: 'Community College of Beaver County', label: 'Community College of Beaver County'),
DropdownMenuEntry(value: 'Community College of Denver', label: 'Community College of Denver'),
DropdownMenuEntry(value: 'Community College of Philadelphia', label: 'Community College of Philadelphia'),
DropdownMenuEntry(value: 'Community College of Rhode Island', label: 'Community College of Rhode Island'),
DropdownMenuEntry(value: 'Community College of the Air Force', label: 'Community College of the Air Force'),
DropdownMenuEntry(value: 'Community College of Vermont', label: 'Community College of Vermont'),
DropdownMenuEntry(value: 'Compu Med Vocational Careers Corp', label: 'Compu Med Vocational Careers Corp'),
DropdownMenuEntry(value: 'Conception Seminary College', label: 'Conception Seminary College'),
DropdownMenuEntry(value: 'Concord University', label: 'Concord University'),
DropdownMenuEntry(value: 'Concorde Career College Aurora Campus', label: 'Concorde Career College Aurora Campus'),
DropdownMenuEntry(value: 'Concorde Career College Dallas', label: 'Concorde Career College Dallas'),
DropdownMenuEntry(value: 'Concorde Career College Grand Prairie', label: 'Concorde Career College Grand Prairie'),
DropdownMenuEntry(value: 'Concorde Career College Memphis', label: 'Concorde Career College Memphis'),
DropdownMenuEntry(value: 'Concorde Career College Portland', label: 'Concorde Career College Portland'),
DropdownMenuEntry(value: 'Concorde Career College San Antonio', label: 'Concorde Career College San Antonio'),
DropdownMenuEntry(value: 'Concorde Career College: Garden Grove', label: 'Concorde Career College: Garden Grove'),
DropdownMenuEntry(value: 'Concorde Career College: Kansas City', label: 'Concorde Career College: Kansas City'),
DropdownMenuEntry(value: 'Concorde Career College: North Hollywood', label: 'Concorde Career College: North Hollywood'),
DropdownMenuEntry(value: 'Concorde Career College: San Bernardino', label: 'Concorde Career College: San Bernardino'),
DropdownMenuEntry(value: 'Concorde Career College: San Diego', label: 'Concorde Career College: San Diego'),
DropdownMenuEntry(value: 'Concorde Career Institute Jacksonville', label: 'Concorde Career Institute Jacksonville'),
DropdownMenuEntry(value: 'Concorde Career Institute Miramar', label: 'Concorde Career Institute Miramar'),
DropdownMenuEntry(value: 'Concorde Career Institute Orlando', label: 'Concorde Career Institute Orlando'),
DropdownMenuEntry(value: 'Concorde Career Institute Tampa', label: 'Concorde Career Institute Tampa'),
DropdownMenuEntry(value: 'Concordia College: Moorhead', label: 'Concordia College: Moorhead'),
DropdownMenuEntry(value: 'Concordia University', label: 'Concordia University'),
DropdownMenuEntry(value: 'Concordia University Ann Arbor', label: 'Concordia University Ann Arbor'),
DropdownMenuEntry(value: 'Concordia University Chicago', label: 'Concordia University Chicago'),
DropdownMenuEntry(value: 'Concordia University Irvine', label: 'Concordia University Irvine'),
DropdownMenuEntry(value: 'Concordia University of Edmonton', label: 'Concordia University of Edmonton'),
DropdownMenuEntry(value: 'Concordia University St. Paul', label: 'Concordia University St. Paul'),
DropdownMenuEntry(value: 'Concordia University Texas', label: 'Concordia University Texas'),
DropdownMenuEntry(value: 'Concordia University Wisconsin', label: 'Concordia University Wisconsin'),
DropdownMenuEntry(value: 'Concordia University: SGW Campus', label: 'Concordia University: SGW Campus'),
DropdownMenuEntry(value: 'Connecticut College', label: 'Connecticut College'),
DropdownMenuEntry(value: 'Connors State College', label: 'Connors State College'),
DropdownMenuEntry(value: 'Conservatory of Music of Puerto Rico', label: 'Conservatory of Music of Puerto Rico'),
DropdownMenuEntry(value: 'Conservatory Of Recording Arts And Sciences', label: 'Conservatory Of Recording Arts And Sciences'),
DropdownMenuEntry(value: 'Continental School of Beauty Culture Mattydale', label: 'Continental School of Beauty Culture Mattydale'),
DropdownMenuEntry(value: 'Continental School of Beauty Culture Rochester', label: 'Continental School of Beauty Culture Rochester'),
DropdownMenuEntry(value: 'Contra Costa College', label: 'Contra Costa College'),
DropdownMenuEntry(value: 'Converse University', label: 'Converse University'),
DropdownMenuEntry(value: 'Cooper Union for the Advancement of Science and Art', label: 'Cooper Union for the Advancement of Science and Art'),
DropdownMenuEntry(value: 'Copiah-Lincoln Community College', label: 'Copiah-Lincoln Community College'),
DropdownMenuEntry(value: 'Copper Mountain College', label: 'Copper Mountain College'),
DropdownMenuEntry(value: 'Coppin State University', label: 'Coppin State University'),
DropdownMenuEntry(value: 'Corban University', label: 'Corban University'),
DropdownMenuEntry(value: 'Cornell College', label: 'Cornell College'),
DropdownMenuEntry(value: 'Cornell University', label: 'Cornell University'),
DropdownMenuEntry(value: 'Cornerstone University', label: 'Cornerstone University'),
DropdownMenuEntry(value: 'Cornish College of the Arts', label: 'Cornish College of the Arts'),
DropdownMenuEntry(value: 'Cortiva Institute King Of Prussia', label: 'Cortiva Institute King Of Prussia'),
DropdownMenuEntry(value: 'Cortiva Institute Maitland', label: 'Cortiva Institute Maitland'),
DropdownMenuEntry(value: 'Cortiva Institute Pompano Beach', label: 'Cortiva Institute Pompano Beach'),
DropdownMenuEntry(value: 'Cosmetology Academy Of Texarkana', label: 'Cosmetology Academy Of Texarkana'),
DropdownMenuEntry(value: 'Cosmetology Training Center', label: 'Cosmetology Training Center'),
DropdownMenuEntry(value: 'Cosmo Beauty Academy', label: 'Cosmo Beauty Academy'),
DropdownMenuEntry(value: 'Cossatot Community College of the University of Arkansas', label: 'Cossatot Community College of the University of Arkansas'),
DropdownMenuEntry(value: 'Cosumnes River College', label: 'Cosumnes River College'),
DropdownMenuEntry(value: 'Cottey College', label: 'Cottey College'),
DropdownMenuEntry(value: 'County College of Morris', label: 'County College of Morris'),
DropdownMenuEntry(value: 'Covenant College', label: 'Covenant College'),
DropdownMenuEntry(value: 'Cowley County Community College', label: 'Cowley County Community College'),
DropdownMenuEntry(value: 'Cox College', label: 'Cox College'),
DropdownMenuEntry(value: 'CQUniversity Rockhampton North', label: 'CQUniversity Rockhampton North'),
DropdownMenuEntry(value: 'Crafton Hills College', label: 'Crafton Hills College'),
DropdownMenuEntry(value: 'Craven Community College', label: 'Craven Community College'),
DropdownMenuEntry(value: 'Crawford County Career And Technical Center Practical Nursing Program', label: 'Crawford County Career And Technical Center Practical Nursing Program'),
DropdownMenuEntry(value: 'Creative Hair School of Cosmetology', label: 'Creative Hair School of Cosmetology'),
DropdownMenuEntry(value: 'Creative Images Institute Of Cosmetology North Dayton', label: 'Creative Images Institute Of Cosmetology North Dayton'),
DropdownMenuEntry(value: 'Creative Images Institute Of Cosmetology South Dayton', label: 'Creative Images Institute Of Cosmetology South Dayton'),
DropdownMenuEntry(value: 'Sovah School of Health Professions', label: 'Sovah School of Health Professions'),
DropdownMenuEntry(value: 'Spa School', label: 'Spa School'),
DropdownMenuEntry(value: 'Spalding University', label: 'Spalding University'),
DropdownMenuEntry(value: 'Spartan College of Aeronautics and Technology', label: 'Spartan College of Aeronautics and Technology'),
DropdownMenuEntry(value: 'Spartanburg Community College', label: 'Spartanburg Community College'),
DropdownMenuEntry(value: 'Spartanburg Methodist College', label: 'Spartanburg Methodist College'),
DropdownMenuEntry(value: 'Spelman College', label: 'Spelman College'),
DropdownMenuEntry(value: 'Spokane Community College', label: 'Spokane Community College'),
DropdownMenuEntry(value: 'Spokane Falls Community College', label: 'Spokane Falls Community College'),
DropdownMenuEntry(value: 'Spoon River College', label: 'Spoon River College'),
DropdownMenuEntry(value: 'Spring Arbor University', label: 'Spring Arbor University'),
DropdownMenuEntry(value: 'Spring Hill College', label: 'Spring Hill College'),
DropdownMenuEntry(value: 'Springfield College', label: 'Springfield College'),
DropdownMenuEntry(value: 'Springfield Technical Community College', label: 'Springfield Technical Community College'),
DropdownMenuEntry(value: 'Srishti Manipal Institute Of Art Design And Technology', label: 'Srishti Manipal Institute Of Art Design And Technology'),
DropdownMenuEntry(value: 'SRM Institute Of Science And Technology', label: 'SRM Institute Of Science And Technology'),
DropdownMenuEntry(value: 'SRM University Delhi-NCR Sonepat', label: 'SRM University Delhi-NCR Sonepat'),
DropdownMenuEntry(value: 'St John Fisher University', label: 'St John Fisher University'),
DropdownMenuEntry(value: 'St John\'s College', label: 'St John\'s College'),
DropdownMenuEntry(value: 'St Josephs University New York', label: 'St Josephs University New York'),
DropdownMenuEntry(value: 'St Josephs University New York - Long Island Campus', label: 'St Josephs University New York - Long Island Campus'),
DropdownMenuEntry(value: 'St. Ambrose University', label: 'St. Ambrose University'),
DropdownMenuEntry(value: 'St. Andrews University', label: 'St. Andrews University'),
DropdownMenuEntry(value: 'St. Augustine College', label: 'St. Augustine College'),
DropdownMenuEntry(value: 'St. Bonaventure University', label: 'St. Bonaventure University'),
DropdownMenuEntry(value: 'St. Catherine University', label: 'St. Catherine University'),
DropdownMenuEntry(value: 'St. Clair County Community College', label: 'St. Clair County Community College'),
DropdownMenuEntry(value: 'St. Cloud Technical and Community College', label: 'St. Cloud Technical and Community College'),
DropdownMenuEntry(value: 'St. Edward\'s University', label: 'St. Edward\'s University'),
DropdownMenuEntry(value: 'St. Francis College', label: 'St. Francis College'),
DropdownMenuEntry(value: 'St. Francis Medical Center College of Nursing', label: 'St. Francis Medical Center College of Nursing'),
DropdownMenuEntry(value: 'St. Francis University', label: 'St. Francis University'),
DropdownMenuEntry(value: 'St. Francis Xavier University', label: 'St. Francis Xavier University'),
DropdownMenuEntry(value: 'St. John Vianney College Seminary', label: 'St. John Vianney College Seminary'),
DropdownMenuEntry(value: 'St. John\'s College (Annapolis, MD)', label: 'St. John\'s College (Annapolis, MD)'),
DropdownMenuEntry(value: 'St. John\'s College (Santa Fe, NM)', label: 'St. John\'s College (Santa Fe, NM)'),
DropdownMenuEntry(value: 'St. John\'s University (Collegeville, MN)', label: 'St. John\'s University (Collegeville, MN)'),
DropdownMenuEntry(value: 'St. John\'s University (Jamaica, NY)', label: 'St. John\'s University (Jamaica, NY)'),
DropdownMenuEntry(value: 'St. Joseph Seminary College', label: 'St. Joseph Seminary College'),
DropdownMenuEntry(value: 'St. Joseph\'s College of Nursing', label: 'St. Joseph\'s College of Nursing'),
DropdownMenuEntry(value: 'St. Lawrence University', label: 'St. Lawrence University'),
DropdownMenuEntry(value: 'St. Louis Community College', label: 'St. Louis Community College'),
DropdownMenuEntry(value: 'St. Louis Community College at Florissant Valley', label: 'St. Louis Community College at Florissant Valley'),
DropdownMenuEntry(value: 'St. Louis Community College at Meramec', label: 'St. Louis Community College at Meramec'),
DropdownMenuEntry(value: 'St. Luke\'s College', label: 'St. Luke\'s College'),
DropdownMenuEntry(value: 'St. Mary\'s College of Maryland', label: 'St. Mary\'s College of Maryland'),
DropdownMenuEntry(value: 'St. Mary\'s University', label: 'St. Mary\'s University'),
DropdownMenuEntry(value: 'St. Mary-of-the-Woods College', label: 'St. Mary-of-the-Woods College'),
DropdownMenuEntry(value: 'St. Norbert College', label: 'St. Norbert College'),
DropdownMenuEntry(value: 'St. Olaf College', label: 'St. Olaf College'),
DropdownMenuEntry(value: 'St. Paul College', label: 'St. Paul College'),
DropdownMenuEntry(value: 'St. Philip\'s College', label: 'St. Philip\'s College'),
DropdownMenuEntry(value: 'St. Thomas Aquinas College', label: 'St. Thomas Aquinas College'),
DropdownMenuEntry(value: 'St. Thomas University (Fredericton, CA)', label: 'St. Thomas University (Fredericton, CA)'),
DropdownMenuEntry(value: 'St. Thomas University (Opa Locka, FL)', label: 'St. Thomas University (Opa Locka, FL)'),
DropdownMenuEntry(value: 'Stacey James Institute', label: 'Stacey James Institute'),
DropdownMenuEntry(value: 'Stage One The Hair School', label: 'Stage One The Hair School'),
DropdownMenuEntry(value: 'Stanbridge University', label: 'Stanbridge University'),
DropdownMenuEntry(value: 'Stanbridge University Los Angeles', label: 'Stanbridge University Los Angeles'),
DropdownMenuEntry(value: 'Standard Healthcare Services College Of Nursing', label: 'Standard Healthcare Services College Of Nursing'),
DropdownMenuEntry(value: 'Stanford University', label: 'Stanford University'),
DropdownMenuEntry(value: 'Stanly Community College', label: 'Stanly Community College'),
DropdownMenuEntry(value: 'Stark State College', label: 'Stark State College'),
DropdownMenuEntry(value: 'State Career College', label: 'State Career College'),
DropdownMenuEntry(value: 'State College of Florida, Manatee-Sarasota', label: 'State College of Florida, Manatee-Sarasota'),
DropdownMenuEntry(value: 'State Fair Community College', label: 'State Fair Community College'),
DropdownMenuEntry(value: 'State Technical College of Missouri', label: 'State Technical College of Missouri'),
DropdownMenuEntry(value: 'State University Of New York At Oswego', label: 'State University Of New York At Oswego'),
DropdownMenuEntry(value: 'State University of New York New Paltz', label: 'State University of New York New Paltz'),
DropdownMenuEntry(value: 'Staunton School Of Cosmetology', label: 'Staunton School Of Cosmetology'),
DropdownMenuEntry(value: 'Stautzenberger College', label: 'Stautzenberger College'),
DropdownMenuEntry(value: 'Stautzenberger College: Brecksville', label: 'Stautzenberger College: Brecksville'),
DropdownMenuEntry(value: 'Stellar Career College', label: 'Stellar Career College'),
DropdownMenuEntry(value: 'Stellenbosch University', label: 'Stellenbosch University'),
DropdownMenuEntry(value: 'Stephen F. Austin State University', label: 'Stephen F. Austin State University'),
DropdownMenuEntry(value: 'Stephens College', label: 'Stephens College'),
DropdownMenuEntry(value: 'Sterling College (Craftsbury Common, VT)', label: 'Sterling College (Craftsbury Common, VT)'),
DropdownMenuEntry(value: 'Sterling College (Sterling, KS)', label: 'Sterling College (Sterling, KS)'),
DropdownMenuEntry(value: 'Stetson University', label: 'Stetson University'),
DropdownMenuEntry(value: 'Stevens Institute of Business & Arts', label: 'Stevens Institute of Business & Arts'),
DropdownMenuEntry(value: 'Stevens Institute of Technology', label: 'Stevens Institute of Technology'),
DropdownMenuEntry(value: 'Stevenson University', label: 'Stevenson University'),
DropdownMenuEntry(value: 'Stewart School', label: 'Stewart School'),
DropdownMenuEntry(value: 'Stillman College', label: 'Stillman College'),
DropdownMenuEntry(value: 'Stockholm School Of Economics', label: 'Stockholm School Of Economics'),
DropdownMenuEntry(value: 'Stockton University', label: 'Stockton University'),
DropdownMenuEntry(value: 'Stone Child College', label: 'Stone Child College'),
DropdownMenuEntry(value: 'Stonehill College', label: 'Stonehill College'),
DropdownMenuEntry(value: 'Strayer University', label: 'Strayer University'),
DropdownMenuEntry(value: 'Strayer University Arlington', label: 'Strayer University Arlington'),
DropdownMenuEntry(value: 'Southwestern Adventist University', label: 'Southwestern Adventist University'),
DropdownMenuEntry(value: 'Southwestern Baptist Theological Seminary', label: 'Southwestern Baptist Theological Seminary'),
DropdownMenuEntry(value: 'Southwestern Christian College', label: 'Southwestern Christian College'),
DropdownMenuEntry(value: 'Southwestern Christian University', label: 'Southwestern Christian University'),
DropdownMenuEntry(value: 'Southwestern College (Chula Vista, CA)', label: 'Southwestern College (Chula Vista, CA)'),
DropdownMenuEntry(value: 'Southwestern College (Winfield, KS)', label: 'Southwestern College (Winfield, KS)'),
DropdownMenuEntry(value: 'Southwestern Community College (Creston, IA)', label: 'Southwestern Community College (Creston, IA)'),
DropdownMenuEntry(value: 'Southwestern Community College (Sylva, NC)', label: 'Southwestern Community College (Sylva, NC)'),
DropdownMenuEntry(value: 'Southwestern Indian Polytechnic Institute', label: 'Southwestern Indian Polytechnic Institute'),
DropdownMenuEntry(value: 'Southwestern Michigan College', label: 'Southwestern Michigan College'),
DropdownMenuEntry(value: 'Southwestern Oklahoma State University', label: 'Southwestern Oklahoma State University'),
DropdownMenuEntry(value: 'Southwestern Oregon Community College', label: 'Southwestern Oregon Community College'),
DropdownMenuEntry(value: 'Southwestern University', label: 'Southwestern University'),
DropdownMenuEntry(value: 'University Of Central Missouri', label: 'University Of Central Missouri'),
DropdownMenuEntry(value: 'University Of Central Oklahoma', label: 'University Of Central Oklahoma'),
DropdownMenuEntry(value: 'University Of Charleston', label: 'University Of Charleston'),
DropdownMenuEntry(value: 'University Of Chicago', label: 'University Of Chicago'),
DropdownMenuEntry(value: 'University Of Chichester', label: 'University Of Chichester'),
DropdownMenuEntry(value: 'University Of Cincinnati', label: 'University Of Cincinnati'),
DropdownMenuEntry(value: 'University Of Cincinnati: Blue Ash College', label: 'University Of Cincinnati: Blue Ash College'),
DropdownMenuEntry(value: 'University Of Cincinnati: Clermont College', label: 'University Of Cincinnati: Clermont College'),
DropdownMenuEntry(value: 'University Of Colorado Boulder', label: 'University Of Colorado Boulder'),
DropdownMenuEntry(value: 'University Of Colorado Colorado Springs', label: 'University Of Colorado Colorado Springs'),
DropdownMenuEntry(value: 'University Of Colorado Denver', label: 'University Of Colorado Denver'),
DropdownMenuEntry(value: 'University Of Connecticut', label: 'University Of Connecticut'),
DropdownMenuEntry(value: 'University Of Connecticut Stamford', label: 'University Of Connecticut Stamford'),
DropdownMenuEntry(value: 'University Of Cosmetology Arts And Sciences Harlingen', label: 'University Of Cosmetology Arts And Sciences Harlingen'),
DropdownMenuEntry(value: 'University Of Dallas', label: 'University Of Dallas'),
DropdownMenuEntry(value: 'University Of Dayton', label: 'University Of Dayton'),
DropdownMenuEntry(value: 'University Of Delaware', label: 'University Of Delaware'),
DropdownMenuEntry(value: 'University Of Denver', label: 'University Of Denver'),
DropdownMenuEntry(value: 'University Of Detroit Mercy', label: 'University Of Detroit Mercy'),
DropdownMenuEntry(value: 'University Of Dubuque', label: 'University Of Dubuque'),
DropdownMenuEntry(value: 'University Of Dundee', label: 'University Of Dundee'),
DropdownMenuEntry(value: 'University Of East Anglia', label: 'University Of East Anglia'),
DropdownMenuEntry(value: 'University Of Edinburgh', label: 'University Of Edinburgh'),
DropdownMenuEntry(value: 'University Of Essex', label: 'University Of Essex'),
DropdownMenuEntry(value: 'University Of Evansville', label: 'University Of Evansville'),
DropdownMenuEntry(value: 'University Of Exeter', label: 'University Of Exeter'),
DropdownMenuEntry(value: 'University Of Findlay', label: 'University Of Findlay'),
DropdownMenuEntry(value: 'University Of Florida', label: 'University Of Florida'),
DropdownMenuEntry(value: 'University Of Florida Online', label: 'University Of Florida Online'),
DropdownMenuEntry(value: 'University Of Georgia', label: 'University Of Georgia'),
DropdownMenuEntry(value: 'University Of Glasgow', label: 'University Of Glasgow'),
DropdownMenuEntry(value: 'University Of Gloucestershire', label: 'University Of Gloucestershire'),
DropdownMenuEntry(value: 'University Of Greenwich', label: 'University Of Greenwich'),
DropdownMenuEntry(value: 'University Of Groningen', label: 'University Of Groningen'),
DropdownMenuEntry(value: 'University Of Guam', label: 'University Of Guam'),
DropdownMenuEntry(value: 'University Of Guelph', label: 'University Of Guelph'),
DropdownMenuEntry(value: 'University Of Hartford', label: 'University Of Hartford'),
DropdownMenuEntry(value: 'University Of Hawaii At Hilo', label: 'University Of Hawaii At Hilo'),
DropdownMenuEntry(value: 'University Of Hawaii At Manoa', label: 'University Of Hawaii At Manoa'),
DropdownMenuEntry(value: 'University Of Hawaii Hawaii Community College', label: 'University Of Hawaii Hawaii Community College'),
DropdownMenuEntry(value: 'University Of Hawaii Honolulu Community College', label: 'University Of Hawaii Honolulu Community College'),
DropdownMenuEntry(value: 'University Of Hawaii Kapiolani Community College', label: 'University Of Hawaii Kapiolani Community College'),
DropdownMenuEntry(value: 'University Of Hawaii Kauai Community College', label: 'University Of Hawaii Kauai Community College'),
DropdownMenuEntry(value: 'University Of Hawaii Leeward Community College', label: 'University Of Hawaii Leeward Community College'),
DropdownMenuEntry(value: 'University Of Hawaii Windward Community College', label: 'University Of Hawaii Windward Community College'),
DropdownMenuEntry(value: 'University Of Hawaii: Maui College', label: 'University Of Hawaii: Maui College'),
DropdownMenuEntry(value: 'University Of Hawaii: West Oahu', label: 'University Of Hawaii: West Oahu'),
DropdownMenuEntry(value: 'University Of Holy Cross', label: 'University Of Holy Cross'),
DropdownMenuEntry(value: 'University Of Hong Kong', label: 'University Of Hong Kong'),
DropdownMenuEntry(value: 'University Of Houston', label: 'University Of Houston'),
DropdownMenuEntry(value: 'University Of Houston-Clear Lake', label: 'University Of Houston-Clear Lake'),
DropdownMenuEntry(value: 'University Of Houston-Downtown', label: 'University Of Houston-Downtown'),
DropdownMenuEntry(value: 'University Of Houston-Victoria', label: 'University Of Houston-Victoria'),
DropdownMenuEntry(value: 'University Of Idaho', label: 'University Of Idaho'),
DropdownMenuEntry(value: 'University Of Illinois Chicago', label: 'University Of Illinois Chicago'),
DropdownMenuEntry(value: 'University Of Illinois Springfield', label: 'University Of Illinois Springfield'),
DropdownMenuEntry(value: 'University Of Illinois Urbana Champaign', label: 'University Of Illinois Urbana Champaign'),
DropdownMenuEntry(value: 'University Of Indianapolis', label: 'University Of Indianapolis'),
DropdownMenuEntry(value: 'University Of Iowa', label: 'University Of Iowa'),
DropdownMenuEntry(value: 'University Of Jamestown', label: 'University Of Jamestown'),
DropdownMenuEntry(value: 'University Of Johannesburg', label: 'University Of Johannesburg'),
DropdownMenuEntry(value: 'University Of Kansas', label: 'University Of Kansas'),
DropdownMenuEntry(value: 'University Of Kent', label: 'University Of Kent'),
DropdownMenuEntry(value: 'University Of Kentucky', label: 'University Of Kentucky'),
DropdownMenuEntry(value: 'University Of La Verne', label: 'University Of La Verne'),
DropdownMenuEntry(value: 'University Of Leeds', label: 'University Of Leeds'),
DropdownMenuEntry(value: 'University Of Leicester', label: 'University Of Leicester'),
DropdownMenuEntry(value: 'University Of Lincoln', label: 'University Of Lincoln'),
DropdownMenuEntry(value: 'University Of Liverpool', label: 'University Of Liverpool'),
DropdownMenuEntry(value: 'University Of Louisiana At Lafayette', label: 'University Of Louisiana At Lafayette'),
DropdownMenuEntry(value: 'University Of Louisiana At Monroe', label: 'University Of Louisiana At Monroe'),
DropdownMenuEntry(value: 'University Of Louisville', label: 'University Of Louisville'),
DropdownMenuEntry(value: 'University Of Lynchburg', label: 'University Of Lynchburg'),
DropdownMenuEntry(value: 'University Of Maine', label: 'University Of Maine'),
DropdownMenuEntry(value: 'University Of Maine At Augusta', label: 'University Of Maine At Augusta'),
DropdownMenuEntry(value: 'University Of Maine At Farmington', label: 'University Of Maine At Farmington'),
DropdownMenuEntry(value: 'University Of Maine At Fort Kent', label: 'University Of Maine At Fort Kent'),
DropdownMenuEntry(value: 'University Of Maine At Presque Isle', label: 'University Of Maine At Presque Isle'),
DropdownMenuEntry(value: 'University Of Management And Technology', label: 'University Of Management And Technology'),
DropdownMenuEntry(value: 'University Of Manchester', label: 'University Of Manchester'),
DropdownMenuEntry(value: 'University Of Manitoba', label: 'University Of Manitoba'),
DropdownMenuEntry(value: 'University Of Mary', label: 'University Of Mary'),
DropdownMenuEntry(value: 'University Of Mary Hardin-Baylor', label: 'University Of Mary Hardin-Baylor'),
DropdownMenuEntry(value: 'University Of Mary Washington', label: 'University Of Mary Washington'),
DropdownMenuEntry(value: 'University Of Maryland Baltimore', label: 'University Of Maryland Baltimore'),
DropdownMenuEntry(value: 'University Of Maryland Global Campus', label: 'University Of Maryland Global Campus'),
DropdownMenuEntry(value: 'University Of Maryland: Baltimore County', label: 'University Of Maryland: Baltimore County'),
DropdownMenuEntry(value: 'University Of Maryland: College Park', label: 'University Of Maryland: College Park'),
DropdownMenuEntry(value: 'University Of Maryland: Eastern Shore', label: 'University Of Maryland: Eastern Shore'),
DropdownMenuEntry(value: 'University Of Massachusetts Amherst', label: 'University Of Massachusetts Amherst'),
DropdownMenuEntry(value: 'University Of Massachusetts Boston', label: 'University Of Massachusetts Boston'),
DropdownMenuEntry(value: 'University Of Massachusetts Dartmouth', label: 'University Of Massachusetts Dartmouth'),
DropdownMenuEntry(value: 'University Of Massachusetts Global', label: 'University Of Massachusetts Global'),
DropdownMenuEntry(value: 'University Of Massachusetts Lowell', label: 'University Of Massachusetts Lowell'),
DropdownMenuEntry(value: 'University Of Melbourne', label: 'University Of Melbourne'),
DropdownMenuEntry(value: 'University Of Memphis', label: 'University Of Memphis'),
DropdownMenuEntry(value: 'University Of Miami', label: 'University Of Miami'),
DropdownMenuEntry(value: 'University Of Michigan Ann Arbor', label: 'University Of Michigan Ann Arbor'),
DropdownMenuEntry(value: 'University Of Michigan: Dearborn', label: 'University Of Michigan: Dearborn'),
DropdownMenuEntry(value: 'University Of Michigan: Flint', label: 'University Of Michigan: Flint'),
DropdownMenuEntry(value: 'University Of Minnesota: Crookston', label: 'University Of Minnesota: Crookston'),
DropdownMenuEntry(value: 'University Of Minnesota: Duluth', label: 'University Of Minnesota: Duluth'),
DropdownMenuEntry(value: 'University Of Minnesota: Morris', label: 'University Of Minnesota: Morris')
          ])
        ],
      ),
    ));
  }
}
